### ISSUE TITLE
loop in install-scripts fails

### ISSUE THREAD

**Issue by kai-e** [nasa/pvslib#14]
Should `loop` in line 34 of install-scripts be `cl-loop`? It seems to fix the issue for me. Could the cause be that at some point in the past `loop` was aliased to `cl-loop` but that aliasing has been dropped in newer emacsen?

(Emacs 28.2, M2 Macbook Air, Mac OS X 13.3.)

**Comment by cesaramh** [comment]
Yes, this is right. I fixed it  and will push it in the next release.

**Comment by cesaramh** [comment]
Closed
